import React, { useState, useEffect } from 'react'
import axios from 'axios'
import jsPDF from 'jspdf'
import * as XLSX from 'xlsx'
import { MdAssessment, MdFilterList, MdDownload, MdCalendarToday, MdTrendingUp, MdPieChart, MdBarChart, MdCheckCircle, MdHourglassEmpty, MdGavel, MdShowChart } from 'react-icons/md'
import { getUser } from '../utils/auth'
import GrievanceChart from '../components/GrievanceChart'
import Toast from '../components/Toast'
import API from '../config/api'

export default function Reports() {
  const user = getUser()
  const [loading, setLoading] = useState(true)
  const [chartData, setChartData] = useState({ byStatus: [], byCategory: [], byMonth: [] })
  const [timeRange, setTimeRange] = useState('all')
  const [toasts, setToasts] = useState([])

  const addToast = (msg, type = 'success') => setToasts(p => [...p, { id: Date.now(), message: msg, type }])
  const removeToast = id => setToasts(p => p.filter(t => t.id !== id))

  const fetchReports = async () => {
    if (!user?.user_id) return
    setLoading(true)
    try {
      const r = await axios.get(`${API}/data/stats/student`)
      if (r.data) {
        setChartData({
          byStatus: r.data.byStatus?.map(s => ({ name: s.status, value: s.count })) || [],
          byCategory: r.data.byCategory?.map(c => ({ name: c.category_name, value: c.count })) || [],
          byMonth: r.data.byMonth?.map(m => ({ name: m.month, value: m.count })) || [],
        })
      }
    } catch {}
    finally { setLoading(false) }
  }

  const exportCSV = () => {
    const csvContent = [
      ['Category', 'Count'],
      ...chartData.byCategory.map(c => [c.name, c.value])
    ].map(row => row.join(',')).join('\n')
    
    const blob = new Blob([csvContent], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `grievance_report_${new Date().toISOString().split('T')[0]}.csv`
    a.click()
    URL.revokeObjectURL(url)
    addToast('CSV report downloaded successfully')
  }

  const exportPDF = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    
    // Header
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text('AGUSAN DEL SUR STATE UNIVERSITY', pageWidth / 2, 20, { align: 'center' })
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Bunawan, Agusan del Sur, Philippines', pageWidth / 2, 26, { align: 'center' })
    
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('Office of Student Affairs and Services', pageWidth / 2, 34, { align: 'center' })
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text('Student Grievance and Disciplinary Committee', pageWidth / 2, 40, { align: 'center' })
    
    // Title
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('GRIEVANCE REPORT', pageWidth / 2, 55, { align: 'center' })
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const reportDate = new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })
    doc.text(`Generated on: ${reportDate}`, pageWidth / 2, 62, { align: 'center' })
    
    // Statistics
    let y = 75
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('Summary Statistics', 20, y)
    y += 10
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const totalFiled = chartData.byStatus.reduce((a, b) => a + b.value, 0)
    doc.text(`Total Filed: ${totalFiled}`, 25, y)
    y += 7
    doc.text(`Resolved: ${chartData.byStatus.find(s => s.name === 'Resolved')?.value || 0}`, 25, y)
    y += 7
    doc.text(`Pending: ${chartData.byStatus.filter(s => ['Submitted', 'Under Review'].includes(s.name)).reduce((a, b) => a + b.value, 0)}`, 25, y)
    y += 7
    doc.text(`In Hearing: ${chartData.byStatus.find(s => s.name === 'Hearing Scheduled')?.value || 0}`, 25, y)
    y += 15
    
    // Cases by Status
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('Cases by Status', 20, y)
    y += 10
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    chartData.byStatus.forEach(item => {
      doc.text(`${item.name}: ${item.value}`, 25, y)
      y += 7
    })
    y += 10
    
    // Cases by Category
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text('Cases by Category', 20, y)
    y += 10
    
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    chartData.byCategory.forEach(item => {
      doc.text(`${item.name}: ${item.value}`, 25, y)
      y += 7
    })
    
    // Footer
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text('This document is generated by Grievance Management System', pageWidth / 2, pageHeight - 15, { align: 'center' })
    
    doc.save(`grievance_report_${new Date().toISOString().split('T')[0]}.pdf`)
    addToast('PDF report downloaded successfully')
  }

  const exportExcel = () => {
    const wb = XLSX.utils.book_new()
    
    // Summary sheet
    const summaryData = [
      ['GRIEVANCE REPORT SUMMARY'],
      ['Generated on:', new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' })],
      [''],
      ['SUMMARY STATISTICS'],
      ['Total Filed', chartData.byStatus.reduce((a, b) => a + b.value, 0)],
      ['Resolved', chartData.byStatus.find(s => s.name === 'Resolved')?.value || 0],
      ['Pending', chartData.byStatus.filter(s => ['Submitted', 'Under Review'].includes(s.name)).reduce((a, b) => a + b.value, 0)],
      ['In Hearing', chartData.byStatus.find(s => s.name === 'Hearing Scheduled')?.value || 0],
      [''],
      ['CASES BY STATUS'],
      ['Status', 'Count'],
      ...chartData.byStatus.map(s => [s.name, s.value]),
      [''],
      ['CASES BY CATEGORY'],
      ['Category', 'Count'],
      ...chartData.byCategory.map(c => [c.name, c.value]),
    ]
    
    const ws = XLSX.utils.aoa_to_sheet(summaryData)
    
    // Set column widths
    ws['!cols'] = [
      { wch: 25 },
      { wch: 15 },
    ]
    
    XLSX.utils.book_append_sheet(wb, ws, 'Summary')
    
    XLSX.writeFile(wb, `grievance_report_${new Date().toISOString().split('T')[0]}.xlsx`)
    addToast('Excel report downloaded successfully')
  }

  useEffect(() => { fetchReports() }, [])

  const stats = [
    { label: 'Total Filed', value: chartData.byStatus.reduce((a, b) => a + b.value, 0), color: 'var(--accent)', icon: <MdAssessment size={20} /> },
    { label: 'Resolved', value: chartData.byStatus.find(s => s.name === 'Resolved')?.value || 0, color: 'var(--green)', icon: <MdCheckCircle size={20} /> },
    { label: 'Pending', value: chartData.byStatus.filter(s => ['Submitted', 'Under Review'].includes(s.name)).reduce((a, b) => a + b.value, 0), color: 'var(--orange)', icon: <MdHourglassEmpty size={20} /> },
    { label: 'In Hearing', value: chartData.byStatus.find(s => s.name === 'Hearing Scheduled')?.value || 0, color: 'var(--purple)', icon: <MdGavel size={20} /> },
  ]

  return (
    <div className="fade-up">
      <div className="page-header">
        <div>
          <h1 className="page-title"><MdAssessment size={24} style={{ verticalAlign: 'middle', marginRight: 8 }} /> My <span className="accent">Reports</span></h1>
          <p className="page-sub">View statistics and analytics of your filed grievances</p>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <select 
            className="filter-select" 
            value={timeRange} 
            onChange={e => setTimeRange(e.target.value)}
          >
            <option value="all">All Time</option>
            <option value="30">Last 30 Days</option>
            <option value="90">Last 90 Days</option>
            <option value="365">Last Year</option>
          </select>
          <button className="btn btn-ghost btn-sm" onClick={fetchReports}>
            <MdFilterList size={14} /> Filter
          </button>
        </div>
      </div>

      <div className="stats-row">
        {stats.map(s => (
          <div className="stat-card" key={s.label}>
            <div className="stat-accent-bar" style={{ background: s.color }} />
            <div className="stat-icon">{s.icon}</div>
            <div className="stat-value" style={{ color: s.color }}>{s.value}</div>
            <div className="stat-label">{s.label}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '1.5rem', marginBottom: '1.5rem' }}>
        <div className="panel">
          <div className="form-section-title">
            <MdPieChart size={14} /> Cases by Status
          </div>
          <GrievanceChart data={chartData.byStatus} color="var(--accent)" />
        </div>

        <div className="panel">
          <div className="form-section-title">
            <MdBarChart size={14} /> Cases by Category
          </div>
          <GrievanceChart data={chartData.byCategory} color="var(--purple)" />
        </div>
      </div>

      <div className="panel">
        <div className="form-section-title">
          <MdTrendingUp size={14} /> Monthly Trend
        </div>
        <GrievanceChart data={chartData.byMonth} color="var(--accent)" />
      </div>

      <div className="panel" style={{ marginTop: '1.5rem' }}>
        <div className="form-section-title">
          <MdDownload size={14} /> Export Reports
        </div>
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
          <button className="btn btn-primary" onClick={exportPDF}>
            <MdDownload size={14} /> Export as PDF
          </button>
          <button className="btn btn-ghost" onClick={exportExcel}>
            <MdDownload size={14} /> Export as Excel
          </button>
          <button className="btn btn-ghost" onClick={exportCSV}>
            <MdDownload size={14} /> Export as CSV
          </button>
        </div>
      </div>

      <Toast toasts={toasts} removeToast={removeToast} />
    </div>
  )
}
